Ignoring state attributes in e2e test
Ignoring computed state attributes due to

Step 2/2 error running import: ImportStateVerify attributes not equivalent. Difference is shown below. The - symbol indicates attributes missing after import.

          map[string]string{
        - 	"edrs_policy_type": "cost",
        + 	"edrs_policy_type": "storage-scaleup",
        - 	"enable_edrs":      "false",
        + 	"enable_edrs":      "true",
        - 	"max_hosts":        "0",
        + 	"max_hosts":        "16",
        - 	"min_hosts":        "0",
        + 	"min_hosts":        "2",
          }
--- FAIL: TestAccResourceVmcClusterRequiredFieldsZerocloud (305.74s)

Signed-off-by: Vasil Atanasov <vasila@vmware.com>